[package]
name = "muda"
version = "0.20.0"
description = "Menu Utilities for Desktop Applications"
edition = "2021"
keywords = ["windowing", "menu"]
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://github.com/tauri-apps/muda"
documentation = "https://docs.rs/muda"
categories = ["gui"]
rust-version = "1.90"
include = [
  "README.md",
  "src/**/*.rs",
  "Cargo.toml",
  "LICENSE-APACHE",
  "LICENSE-MIT",
  "LICENSE.spdx",
]

[features]
default = ["libxdo", "gtk"]
libxdo = ["dep:libxdo"]
gtk = ["dep:gtk"]
gtk4 = ["dep:gtk4"]
common-controls-v6 = []
serde = ["dep:serde", "dpi/serde", "keyboard-types/serde"]

[dependencies]
crossbeam-channel = "0.5"
keyboard-types = "0.8"
once_cell = "1"
thiserror = "2"
serde = { version = "1", optional = true }
dpi = "0.1"

[target.'cfg(target_os = "windows")'.dependencies.windows-sys]
version = ">=0.60, <=0.61"
features = [
  "Win32_UI_WindowsAndMessaging",
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_UI_Shell",
  "Win32_Globalization",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_System_SystemServices",
  "Win32_UI_Accessibility",
  "Win32_UI_HiDpi",
  "Win32_System_LibraryLoader",
  "Win32_UI_Controls",
]

[target.'cfg(any(target_os = "linux", target_os = "dragonfly", target_os = "freebsd", target_os = "netbsd", target_os = "openbsd"))'.dependencies]
gtk = { version = "0.18", optional = true }
gtk4 = { version = "0.11", optional = true, features = ["v4_12"] }
libxdo = { version = "0.6.0", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.1"
objc2-core-foundation = { version = "0.3.0", default-features = false, features = [
  "std",
  "CFCGTypes",
] }
objc2-foundation = { version = "0.3.0", default-features = false, features = [
  "std",
  "NSAttributedString",
  "NSData",
  "NSDictionary",
  "NSGeometry",
  "NSRange",
  "NSString",
  "NSThread",
] }
objc2-app-kit = { version = "0.3.0", default-features = false, features = [
  "std",
  "objc2-core-foundation",
  "NSApplication",
  "NSAttributedString",
  "NSCell",
  "NSColor",
  "NSEvent",
  "NSFont",
  "NSImage",
  "NSMenu",
  "NSMenuItem",
  "NSResponder",
  "NSRunningApplication",
  "NSScreen",
  "NSView",
  "NSWindow",
] }
png = "0.18"

[dev-dependencies]
winit = "0.30"
tao = "0.36"
wry = "0.56"
image = { version = "0.25", default-features = false, features = ["png"] }
winit-gtk4 = { package = "winit", git = "https://github.com/tauri-apps/winit-gtk4", default-features = false, features = [
  "gtk4",
] }

[[example]]
name = "tao"
required-features = ["gtk"]

[[example]]
name = "winit_gtk4"
required-features = ["gtk4"]

[[example]]
name = "wry"
required-features = ["gtk"]
