[package]
name = "windows-common-controls-v6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["libxdo", "gtk3"]
libxdo = ["muda/libxdo"]
gtk3 = ["muda/gtk3"]

[dependencies]
muda = { path = "../../", default-features = false, features = ["common-controls-v6"] }
tao = "0.37"
image = { version = "0.25", default-features = false, features = ["png"] }

[target."cfg(target_os = \"windows\")".dependencies.windows-sys]
version = "0.61"
features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation"]

[build-dependencies]
embed-resource = "3"

[patch.crates-io]
tao = { git = "https://github.com/tauri-apps/tao.git", branch = "gtk-0.19" }
